create database petadoption;
use petadoption;
create table USERS(NAME char(20),BREEDTYPE char(20), PRIZE varchar(20));
INSERT INTO USERS VALUES('ABHIRAM','GERMAN',30000);
INSERT INTO USERS VALUES('SURESH','GOLDEN',40000);
INSERT INTO USERS VALUES('RAMESH','GERMAN',25000);

CREATE TABLE ANIMALSLIST(id VARCHAR(20) NOT NULL, name CHAR(20), breed CHAR(20), color CHAR(20), gender CHAR(20), status VARCHAR(20));
INSERT INTO ANIMALSLIST VALUES('25484A78', 'SNOOPY','GERMANY','WHITE','MALE','1');
INSERT INTO ANIMALSLIST VALUES('25ACA78', 'DOG1','GOLDEN','BROWN','FEMALE','0');
INSERT INTO ANIMALSLIST VALUES('25CBD78', 'DOG2','GERMAN','BLACK','MALE',1);

SELECT * FROM ANIMALSLIST WHERE gender='MALE';
update ANIMALSLIST SET NAME='BRODDY' WHERE NAME ='DOG2';
UPDATE ANIMALSLIST SET STATUS=1 WHERE ID='25ACA78';
SELECT * FROM USERS ORDER BY PRIZE DESC;
SELECT * FROM USERS ORDER BY PRIZE ;
UPDATE ANIMALSLIST SET STATUS=0 WHERE ID='25ACA78';
SELECT * FROM ANIMALSLIST ORDER BY STATUS;
INSERT INTO animalsLIST (id, name, breed, color, gender, status) VALUES ('8935', 'Spot', 'Dalmation', 'Black and White', 'Male', 0);
CREATE TABLE adoptions (animal_id varchar(20) NOT NULL, name char(20), contact char(20), date TIMESTAMP);
INSERT INTO adoptions (animal_id, name, contact,date) VALUES ('945454', 'Pinocchio', 'realboy@cockroac');
DROP TABLE ADOPTIONS;
CREATE TABLE adoptions (animal_id varchar(20) NOT NULL, name char(20), contact char(20), dates date);
INSERT INTO adoptions (animal_id, name, contact,dateS) VALUES ('945454', 'Pinocchio', 'realboy', CURRENT_TIMESTAMP);
INSERT INTO ANIMALSLIST VALUES(52684,'DOG4','GERMAN','BLACK','MALE',0);
DELETE FROM ANIMALSLIST WHERE NAME='DOG4';
INSERT INTO ANIMALSLIST VALUES(52684,'DOG4','GERMAN','BLACK','MALE',0);
INSERT INTO ANIMALSLIST VALUES(526884,'DOG5','GERMAN','WHITE','FEMALE',0);
INSERT INTO ANIMALSLIST VALUES(5268,'DOG6','GERMAN','BLACK','MALE',0);
INSERT INTO ANIMALSLIST VALUES(59884,'DOG7','GERMAN','BLACK','FEMALE',0);
UPDATE ANIMALSLIST SET STATUS=1 WHERE NAME='DOG4';
ALTER TABLE USERS DROP COLUMN BREEDTYPE;
ALTER TABLE USERS ADD ANIMAL_ID VARCHAR(20);
DELETE FROM USERS WHERE NAME='ABHIRAM';
DELETE FROM USERS WHERE NAME='SURESH';
DELETE FROM USERS WHERE NAME='RAMESH';
INSERT INTO USERS VALUES('ABHI',25000,52684);

CREATE TABLE SHELTER(ID VARCHAR(10), NAME VARCHAR(20), LOCATION VARCHAR(50));
INSERT INTO SHELTER VALUES (52684, '4 Homes', 'Red City');
create table student (id varchar(25), name varchar(25),country varchar(25));
insert into student values(580, 'abhiram', 'india');
/* Truncate command : */
truncate table student;
drop table student;
SELECT * FROM USERS;
SELECT * FROM ANIMALSLIST;
SELECT * FROM SHELTER;


/*
SELECT * FROM student;*/
/*
CREATE TABLE ANIMALSLIST(id VARCHAR(20) NOT NULL, name CHAR(20), breed CHAR(20), color CHAR(20), gender CHAR(20), status VARCHAR(20));
create table USERS(NAME char(20),BREEDTYPE char(20), PRIZE varchar(20));
	*/
